# Docker
# Build a Docker image

trigger:
- master

resources:
- repo: self

variables:
 tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
        - task: Docker@2
          displayName: Build and push image to regestery
          inputs: 
           command: buildAndPush
           repository: FootBallScore/FootBallScore
           containerRegistry: FootballscoreRepo
           Dockerfile: '**/Dockerfile'
           tags: |
             $(tag)
             latest



